site_name: Lxj's Blog
site_url: https://aluo-Lxj.github.io/lxj-blog
site_description: To see the world in a different way.
site_author: lxj
theme:
  name: material
  custom_dir: docs/overrides #覆写路径
  font:
    text: Bitter
    code: Roboto Mono
  logo: assets/dog.jpg
  favicon: assets/blog.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon:  material/brightness-auto
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: white # 上方的
      accent: blue # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/toggle-switch # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式
  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - navigation.expand  # 打开Tab时左侧目录全部展开
    - navigation.instant # 侧边栏目录的瞬时加载
    - navigation.sections # 侧边栏目录的分组
    - navigation.search.suggest # 搜索框建议
    - navigation.tracking # 侧边栏目录的滚动跟踪
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - navigation.search # 搜索框
    - navigation.search.highlight # 搜索框高亮
    - navigation.search.share # 搜索框分享
    - navigation.search.smooth_scroll # 搜索框平滑滚动
    - navigation.search.smooth_scroll_offset: 100px # 滚动偏移量
    - navigation.search.smooth_scroll_duration: 300ms # 滚动持续时间
    - navigation.search.smooth_scroll_easing: ease-in-out # 滚动动画类型
    - navigation.search.smooth_scroll_easing: ease-in-out # 滚动动画类型
    - toc.integrate: true # 集成目录到侧边栏中，默认 false
    - toc.integrate.level: 2 # 集成目录的层级，默认 2
    - toc.integrate.max_level: 3 # 集成目录的最大层级，默认 3
    - toc.integrate.min_level: 1 # 集成目录的最小层级，默认 1
    - content.tabs.link # 标签页（Tabs）支持点击标题跳转锚点，便于 URL 定位。
    - content.tooltips # 支持 <abbr> 和带 title 属性的元素显示悬浮提示。
    - content.code.copy #代码复制按钮
    # - content.action.edit # 在每篇文档页面顶部或底部显示“编辑此页”的按钮（一般跳转 GitHub）
    # - content.action.view # 显示“查看此页源码”的按钮，通常跳转 GitHub 源文件地址
    - content.code.annotate # 允许在代码块中嵌入注释（用 #: 注释 的方式），呈现为左边的小提示。
  languages: zh-Hans # 中文简体
  icon:
    repo: fontawesome/brands/github # 图标
    logo: logo
edit_uri: edit/main/docs # 编辑按钮跳转的链接
repo_url: https://github.com/aluo-Lxj
repo_name: Lxj's Github
nav:
  # - Home: index.md
  - Blog:
    - Hi: blog/blog_intro.md
  - About:
    - About: about/about.md
  - Home:
    - Home: index.md
extra:    
  alternate:
    - name: English
      link: https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp 
      lang: en
  generator: false
