site_name: Lxj's Blog
site_url: https://aluo-Lxj.github.io/lxj-blog
site_description: To see the world in a different way.
site_author: lxj

theme:
  name: material
  custom_dir: docs/overrides
  font:
    text: Bitter
    code: Roboto Mono
  logo: assets/dog.jpg
  favicon: assets/blog.png
  languages: zh-Hans # 中文简体
  icon:
    repo: fontawesome/brands/github
    logo: logo
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 关闭自动模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: black
      toggle:
        icon: material/toggle-switch
        name: 切换至夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至日间模式
  features:
    - announce.dismiss
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - navigation.expand
    - navigation.sections
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.code.annotate

edit_uri: edit/main/docs
repo_url: https://github.com/aluo-Lxj
repo_name: Lxj's Github

nav:
  - Record:
    - Hi: read/read_intro.md
  - Blog:
    - index: blog/index.md
  - About:
    - About: about/about.md
  - Home:
    - Home: index.md

extra:
  alternate:
    - name: English
      link: https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
      lang: en
  generator: false

plugins:
  - blog:
      blog_dir: blog
      blog_toc: true
      post_dir: "{blog}/articles"
      post_date_format: long
  - search

# 目录配置
docs_dir: docs
site_dir: site
use_directory_urls: true

# 可爱样式
extra_css:
  - stylesheets/custom.css
